# Generated by Django 3.2.9 on 2021-12-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbi', '0002_auto_20211211_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
