# Generated by Django 3.2.9 on 2021-12-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbi', '0003_account_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='challanfile',
            name='cash_deposit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
