# Generated by Django 4.0.1 on 2022-02-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbi', '0005_otherbankchallanfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pan',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
