# Generated by Django 4.0.1 on 2022-02-01 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbi', '0006_alter_account_pan'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=100)),
                ('ac_no', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('pan', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='otherbankchallanfile',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sbi.otherbankaccount'),
        ),
    ]
