# Generated by Django 4.0.1 on 2022-02-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbi', '0007_otherbankaccount_otherbankchallanfile_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challanfile',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='challanfile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
