# Generated by Django 4.0.1 on 2022-02-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbi', '0008_remove_challanfile_account_account_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adaar', models.CharField(max_length=100)),
            ],
        ),
    ]
