# Generated by Django 4.0.1 on 2022-03-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbi', '0009_depositor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherbankchallanfile',
            name='account',
        ),
        migrations.AddField(
            model_name='otherbankchallanfile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
