# Generated by Django 4.0.1 on 2022-03-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbi', '0009_depositor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('account', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='otherbankaccount',
            old_name='telephone',
            new_name='bank',
        ),
        migrations.RemoveField(
            model_name='otherbankaccount',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='otherbankchallanfile',
            name='account',
        ),
        migrations.AddField(
            model_name='otherbankaccount',
            name='branch',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherbankchallanfile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
