# Generated by Django 4.0.1 on 2022-03-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbi', '0010_remove_otherbankchallanfile_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherbankaccount',
            name='bank',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherbankaccount',
            name='branch',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
