# Generated by Django 4.0.1 on 2022-05-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbi', '0012_account_user_applicant_user_challanfile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='telephone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
